name: odoo_rpc
description: Odoo RPC Client library for Dart with session changes tracking via steam.
version: 0.4.5
homepage: https://github.com/ERP-Ukraine/odoo-rpc-dart
repository: https://github.com/ERP-Ukraine/odoo-rpc-dart
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.0
  crypto: ^3.0.0
  pedantic: ^1.11.0

dev_dependencies:
  test: ^1.16.5
